gpub.book.latex.defaultTemplate = [
'\\documentclass[letterpaper,12pt]{memoir}',
'\\usepackage{color}',
'\\usepackage{wrapfig}',
'\\usepackage{setspace}',
'\\usepackage{unicode}',
'\\usepackage[margin=1in]{geometry}',

'%%% Define any extra packages %%%',
'{{init}}',

'',
'\\setlength{\\parskip}{0.5em}',
'\\setlength{\\parindent}{0pt}',
'',

'%%% Diagram Figure defs.',
'% Must expose two commands',
'%  \\gofigure  (mainline diagrams)',
'%  \\godiagram (variation diagrams)',
'{{diagramWrapperDef}}',
'',

'%%% Define the main title %%%',
'\\definecolor{light-gray}{gray}{0.55}',
'\\newcommand*{\\mainBookTitle}{\\begingroup',
'  \\raggedleft',
'  {{#authors}}',
'     {\\Large {{name}} }',
'  {{/authors}}',
'  \\vspace*{5 em}',
'  {\\textcolor{light-gray}{\\Huge {{title}} }\\\\',
'  \\vspace*{\\baselineskip}',
'  {\\small \\bfseries {{subtitle}} }\\par',
'  \\vfill',
'  {\\Large {{publisher}} }\\par',
'  \\vspace*{2\\baselineskip}',
'\\endgroup}',

'',
'\\begin{document}',
'',
'\\pagestyle{empty}',
'\\mainBookTitle',
'\\newpage',
'\\tableofcontents',
'',
'\\chapterstyle{section}',
'\\pagestyle{companion}',
'\\makepagestyle{headings}',
'\\renewcommand{\\printchapternum}{\\space}',
'\\makeevenhead{headings}{\\thepage}{}{\\slshape\\leftmark}',
'\\makeoddhead{headings}{\\slshape\\rightmark}{}{\\thepage}',
'',

'%%% The content. %%%',
'{{content}}',
'',
'\\end{document}'].join('\n');
