/*
 GPub: A Go publishing platform, built on Glift

 @copyright Josh Hoak
 @license MIT License (see LICENSE.txt)
 --------------------------------------
*/
(function(a){var b=b||a.gpub||{};a&&(a.gpub=b)})(window);gpub.global={version:"0.1.0"};gpub.book={bookFormat:{HTML:"HTML",LATEX:"LATEX"}};gpub.book.htmlBook={create:function(a,b){}};
gpub.book.latex={generate:function(a,b,c){if(!a)throw Error("Options must be defined. Was: "+a);b=b||gpub.templates.latexBase;c=c||gpub.diagrams.diagramType.GOOE;a=glift.widgets.createNoDraw(a);b=gpub.templates.parseLatexTemplate(b);c=gpub.diagrams[glift.enums.toCamelCase(c)].latexHeaders;var d=gpub.diagrams.latex;b.setExtraPackages(c.packageDef()).setDiagramTypeDefs(c.extraDefs()).setDiagramWrapperDefs(d.diagramDefs()).setTitleDef(this.basicTitleDef("Relentless","Gu Li vs Lee Sedol",["Younggil An",
"David Ormerod","Josh Hoak"],"Go Game Guru"));c=[];for(d=0;d<a.sgfCollection.length;d++){var f=a.loadSgfStringSync(a.getSgfObj(d)),e=glift.rules.movetree.getFromSgf(f.sgfString,f.initialPosition),g=glift.flattener.flatten(e,{nextMovesTreepath:f.nextMovesPath,boardRegion:f.boardRegion}),h=gpub.diagrams.diagramPurpose.GAME_REVIEW;0==e.node().getNodeNum()&&0==f.nextMovesPath.length&&(h=gpub.diagrams.diagramPurpose.SECTION_INTRO);f=gpub.diagrams.forPurpose(g,gpub.diagrams.diagramType.GOOE,gpub.book.bookFormat.LATEX,
h,{chapterTitle:"Chapter "+d});c.push(f);c.push("\\newpage")}return b.setContent(c.join("\n")).compile()},basicTitleDef:function(a,b,c,d){for(var f=["\\definecolor{light-gray}{gray}{0.55}","\\newcommand*{\\mainBookTitle}{\\begingroup","  \\raggedleft"],e=0;e<c.length;e++)f.push("  {\\Large "+c[e]+"} \\\\"),0===e?f.push("  \\vspace*{0.5 em}"):e<c.length-1&&f.push("  \\vspace*{0.5 em}");return f.concat(["  \\vspace*{5 em}","  {\\textcolor{light-gray}{\\Huge "+a+"}}\\\\","  \\vspace*{\\baselineskip}",
"  {\\small \\bfseries "+b+"}\\par","  \\vfill","  {\\Large "+d+"}\\par","  \\vspace*{2\\baselineskip}","\\endgroup}"]).join("\n")},renderPage:function(a){a.push("\\newpage");return a.join("\n")}};
gpub.book.manager={toBook:function(a,b){var c=[],d=glift.enums.showVariations.NEVER,f=gpub.diagrams.gooe,e=gpub.diagrams.latex,g=gpub.book.manager,h=a.bookData;c.push(e.basicHeader());c.push(f.gooeDefs());c.push(e.generateTitleDef(h.title,h.subtitle,h.authors,h.publisher));c.push("");c.push(e.diagramLabelMacros());c.push(e.startDocument());a.prepopulateCache(function(){for(var f=h.diagramsPerPage,n=1,s=1,t=1,m=0,u=a.sgfList.length;m<u;m++){var p=a.getSgfObj(m),v=p.boardRegion,q=glift.rules.treepath.parseInitPosition(p.initialPosition),
r=[];a.getSgfString(p,function(a){var b=glift.rules.movetree.getFromSgf(a.sgfString,q),e=b.onMainline();e?t++:s++;if(h.autoNumber){var k=glift.rules.treepath.findNextMovesPath(b),b=k.movetree;q=k.treepath;r=k.nextMoves}var k=glift.rules.goban.getFromMoveTree(b).goban,m=e?b.node().getNodeNum()+1:1,b=glift.bridge.flattener.flatten(b,k,v,d,r,m),k="";a.bookData.showDiagram&&(k=g.createDiagram(b,a.bookData));e=g.typesetDiagram(k,b.comment,a.bookData,b.collisions,e);!a.bookData.chapterTitle&&n<f?(c.push("\\newpage"),
n++):n=1;c.push(e)})}c.push(e.basicFooter);b(c.join("\n"))})},createDiagram:function(a,b){var c=gpub.diagrams.gooe,d=gpub.diagrams.diagramSize.NORMAL;b.chapterTitle&&(d=gpub.diagrams.diagramSize.LARGE);d=c.diagramArray(a,d);return c.diagramArrToString(d)}};gpub.gen={};
gpub.gen.collection={fromGames:function(a){for(var b={divId:null,sgfCollection:[],sgfMapping:{}},c=0;a&&c<a.length;c++){var d=a[c],f=glift.sgf.parse(d),e=f.properties().getOneValue("GN")||"sgf:"+c;b.sgfMapping[e]=d;b.sgfCollection=b.sgfCollection.concat(this.fromMovetree(f,e))}return b},fromMovetree:function(a,b){for(var c=[],d=[],f=a.node();f;){if(!a.properties().getOneValue("C")&&0<f.numChildren())f=a.node(),d=d.concat(this.getVariationPaths(a));else{var e=glift.rules.treepath.findNextMovesPath(a);
c.push(this.createExample(b,e.treepath,e.nextMoves));d=d.concat(this.getVariationPaths(a));for(e=0;e<d.length;e++){var g=a.getTreeFromRoot(d[e]),g=glift.rules.treepath.findNextMovesPath(g);c.push(this.createExample(b,g.treepath,g.nextMoves))}d=[]}f=f.getChild(0);a.moveDown()}return c},getVariationPaths:function(a){a=a.newTreeRef();var b=[];if(!a.node().getParent())return b;a.moveUp();for(var c=1;c<a.node().numChildren();c++){var d=a.newTreeRef();d.moveDown(c);d.recurse(function(a){a.properties().getOneValue("C")&&
b.push(a.treepathToHere())})}return b},createExample:function(a,b,c,d){d=d||glift.enums.boardRegions.ALL;if(!glift.enums.boardRegions[d])throw Error("Unknown board region: "+d);var f=glift.rules.treepath.toInitPathString,e=glift.rules.treepath.toFragmentString;return{widgetType:"EXAMPLE",alias:a,initialPosition:f(b),nextMovesPath:e(c),boardRegion:d}}};
gpub.diagrams={diagramType:{GOOE:"GOOE",IGO:"IGO",PDF:"PDF"},diagramPurpose:{SECTION_INTRO:"SECTION_INTRO",GAME_REVIEW:"GAME_REVIEW",GAME_REVIEW_CHAPTER:"GAME_REVIEW_CHAPTER",PROBLEM:"PROBLEM",PROBLEM_SOLUTION:"PROBLEM_SOLUTION"},sizes:{NORMAL:"NORMAL",LARGE:"LARGE"},forPurpose:function(a,b,c,d,f){if(!b||!gpub.diagrams.diagramType[b])throw Error("Unknown diagram type: "+b);if(!c||!gpub.book.bookFormat[c])throw Error("Unknown diagram type: "+c);if(!d||!gpub.diagrams.diagramPurpose[d])throw Error("Unknown diagram type: "+
d);f=f||{};b=gpub.diagrams.fromFlattened(a,b);var e=null;switch(c){case "LATEX":e=gpub.diagrams.latex;break;default:throw Error("Unsupported book format: "+c);}c=null;switch(d){case "GAME_REVIEW":case "GAME_REVIEW_CHAPTER":case "SECTION_INTRO":c=gpub.diagrams.labelForCollisions(a.collisions());break;default:c=""}return e.typeset(b,d,a.comment(),c,a.isOnMainPath(),f)},create:function(a,b,c,d,f){a=this.flatten(a,c,d,f);return this.fromFlattened(a,b)},flatten:function(a,b,c,d){b=b||[];c=c||[];a=glift.rules.movetree.getFromSgf(a,
b);return glift.flattener.flatten(a,{nextMovesTreepath:c,boardRegion:d})},fromFlattened:function(a,b){switch(b){case "GOOE":return gpub.diagrams.gooe.create(a);default:throw Error("Not currently supported: "+b);}},labelForCollisions:function(a){if(!a||"array"!==glift.util.typeOf(a)||0===a.length)return"";for(var b=[],c=0;c<a.length;c++){var d=a[c];b.push((d.color===glift.enums.states.BLACK?"Black":"White")+" "+d.mvnum+" at "+d.label)}return b.join(", ")+"."}};
gpub.diagrams.gooe={create:function(a,b){return gpub.diagrams.gooe.gooeStringArray(a,b).join("\n")},gooeStringArray:function(a,b){for(var c="LARGE"===b?"{\\bgoo":"{\\goo",d=gpub.diagrams.gooe.gooeBoard(a,b),c=[c],f=0,d=d.boardArray();f<d.length;f++)c.push(d[f].join(""));c.push("}");return c},gooeBoard:function(a,b){var c=glift.flattener.symbolStr,d=gpub.diagrams.gooe.symbolMap;return a.board().transform(function(a,e,g){e=c(a.base());a.mark()&&a.stone()?e=c(a.stone())+"_"+c(a.mark()):a.stone()?e=c(a.stone()):
a.mark()&&(e=c(a.mark()));g=e+"_"+b;var h="",h=d[g]?d[g]:d[e]?d[e]:d.EMPTY;a.textLabel()&&(h=h.replace("%s",a.textLabel()));return h})}};
gpub.diagrams.gooe.latexHeaders={packageDef:function(){return"\\usepackage{gooemacs}"},defs:{sizeDefs:"% Size definitions;\\newdimen\\bigRaise;\\bigRaise=4.3pt;\\newdimen\\smallRaise;\\smallRaise=3.5pt;\\newdimen\\inlineRaise;\\inlineRaise=3.5pt".split(";"),bigBoardDefs:["% Big-sized board defs","\\def\\eLblBig#1{\\leavevmode\\hbox to \\goIntWd{\\hss\\raise\\bigRaise\\hbox{\\tenpointeleven{#1}}\\hss}}","\\def\\goWsLblBig#1{\\leavevmode\\setbox0=\\hbox{\\0??!}\\rlap{\\0??!}\\raise\\bigRaise\\hbox to \\wd0{\\hss\\tenpointeleven{#1}\\hss}}",
"\\def\\goBsLblBig#1{\\leavevmode\\setbox0=\\hbox{\\0??@}\\rlap{\\0??@}\\raise\\bigRaise\\hbox to \\wd0{\\hss\\color{white}\\tenpointeleven{#1}\\color{white}\\hss}}"],normalBoardDefs:["% Normal-sized board defs","\\def\\eLbl#1{\\leavevmode\\hbox to \\goIntWd{\\hss\\raise\\smallRaise\\hbox{\\tenpoint{#1}}\\hss}}","\\def\\goWsLbl#1{\\leavevmode\\setbox0=\\hbox{\\0??!}\\rlap{\\0??!}\\raise\\smallRaise\\hbox to \\wd0{\\hss\\eightpointnine{#1}\\hss}}","\\def\\goBsLbl#1{\\leavevmode\\setbox0=\\hbox{\\0??@}\\rlap{\\0??@}\\raise\\smallRaise\\hbox to \\wd0{\\hss\\color{white}\\eightpointnine{#1}\\color{white}\\hss}}"]},
extraDefs:function(a){var b=gpub.diagrams.gooe.latexHeaders.defs;a=a||"cmss";return["% Gooe font definitions","\\font\\tenpoint="+a+"10","\\font\\tenpointeleven="+a+"10 at 11pt","\\font\\eightpoint="+a+"8","\\font\\eightpointnine="+a+"8 at 9pt"].concat(b.sizeDefs).concat(b.bigBoardDefs).concat(b.normalBoardDefs).join("\n")}};
gpub.diagrams.gooe.symbolMap={EMPTY:"\\eLbl{_}",TL_CORNER:"\\0??<",TR_CORNER:"\\0??>",BL_CORNER:"\\0??,",BR_CORNER:"\\0??.",TOP_EDGE:"\\0??(",BOT_EDGE:"\\0??)",LEFT_EDGE:"\\0??[",RIGHT_EDGE:"\\0??]",CENTER:"\\0??+",CENTER_STARPOINT:"\\0??*",BSTONE:"\\0??@",WSTONE:"\\0??!",BSTONE_TRIANGLE:"\\0??S",WSTONE_TRIANGLE:"\\0??s",TRIANGLE:"\\0??3",BSTONE_SQUARE:"\\0??S",WSTONE_SQUARE:"\\0??s",SQUARE:"\\0??2",BSTONE_CIRCLE:"\\0??C",WSTONE_CIRCLE:"\\0??c",CIRCLE:"\\0??1",BSTONE_XMARK:"\\0??X",WSTONE_XMARK:"\\0??x",
XMARK:"\\0??4",BSTONE_TEXTLABEL:"\\goBsLbl{%s}",WSTONE_TEXTLABEL:"\\goWsLbl{%s}",TEXTLABEL:"\\eLbl{%s}",BSTONE_TEXTLABEL_LARGE:"\\goBsLblBig{%s}",WSTONE_TEXTLABEL_LARGE:"\\goWsLblBig{%s}",TEXTLABEL_LARGE:"\\eLblBig{%s}"};gpub.diagrams.igo={create:function(a){}};gpub.diagrams.pdf={create:function(a){}};
gpub.diagrams.latex={sanitize:function(a){a=a.replace("$","\\$");return a=a.replace("#","\\#")},typeset:function(a,b,c,d,f,e){c=this.sanitize(c);var g=glift.enums.toCamelCase(b),g=gpub.diagrams.latex[g];switch(b){case "GAME_REVIEW":b=f?"\\gofigure":"\\godiagram",d&&(b+="\n\n \\subtext{"+d+"}"),d=b}return g(a,c,d,e)},sectionIntro:function(a,b,c,d){return["\\chapter{"+(d.chapterTitle||"Chapter")+"}",b].join("\n")},gameReview:function(a,b,c){return["\n\\rule{\\textwidth}{0.5pt}\n\n\\begin{minipage}[t]{0.5\\textwidth}",
a,c,"\\end{minipage}\n\\begin{minipage}[t]{0.5\\textwidth}\n\\setlength{\\parskip}{0.5em}",b,"\\end{minipage}\n\\vfill"].join("\n")},gameReviewChapter:function(a,b,c,d){return["\\chapter{"+d+"}","{\\centering",a,"}",c,"",b,"\\vfill"].join("\n")}};gpub.diagrams.latex.diagramDefs=function(a){return"% Mainline Diagrams. reset at parts\n\\newcounter{GoFigure}[part]\n\\newcommand{\\gofigure}{%\n \\stepcounter{GoFigure}\n \\centerline{\\textit{Figure.\\thinspace\\arabic{GoFigure}}}\n}\n% Variation Diagrams. reset at parts.\n\\newcounter{GoDiagram}[part]\n\\newcommand{\\godiagram}{%\n \\stepcounter{GoDiagram}\n \\centerline{\\textit{Diagram.\\thinspace\\arabic{GoDiagram}}}\n}\n\\newcommand{\\subtext}[1]{\\centerline{\\textit{#1}}}\n"};
gpub.templates={};gpub.templates._Template=function(a,b){this._sections=a;this._paramMap=b;this._paramContent={}};gpub.templates._Template.prototype={compile:function(){var a=this._sections.slice(0),b;for(b in this._paramMap)a[this._paramMap[b]]=this._paramContent[b]||"";return a.join("")},hasParam:function(a){return!!this._paramMap[a]},setParam:function(a,b){if(!this._paramMap[a])throw Error("Unknown key: "+a);this._paramContent[a]=b.toString()}};gpub.templates.latexBase="\\documentclass[letterpaper,12pt]{memoir}\n\\usepackage{color}\n\\usepackage{wrapfig}\n\\usepackage{setspace}\n\\usepackage{unicode}\n\\usepackage[margin=1in]{geometry}\n%%% Define any extra packages %%%\n{{ extraPackages }}\n\n\\setlength{\\parskip}{0.5em}\n\\setlength{\\parindent}{0pt}\n\n%%% Extra defs\n% Necessary for the particular digaram type.\n{{ diagramTypeDefs }}\n\n%%% Diagram Figure defs.\n% Must expose two commands\n%  \\gofigure  (mainline diagrams)\n%  \\godiagram (variation diagrams)\n{{ diagramWrapperDefs }}\n\n%%% Define the main title %%%\n{{ mainBookTitleDef }}\n\n\\begin{document}\n\n\\pagestyle{empty}\n\\mainBookTitle\n\\newpage\n\\tableofcontents\n\n\\chapterstyle{section}\n\\pagestyle{companion}\n\\makepagestyle{headings}\n\\renewcommand{\\printchapternum}{\\space}\n\\makeevenhead{headings}{\\thepage}{}{\\slshape\\leftmark}\n\\makeoddhead{headings}{\\slshape\\rightmark}{}{\\thepage}\n\n%%% The content. %%%\n{{ content }}\n\n\\end{document}";
gpub.templates.parseLatexTemplate=function(a){var b=gpub.templates.parse(a);["extraPackages","diagramTypeDefs","diagramWrapperDefs","mainBookTitleDef","content"].forEach(function(a){if(!b.hasParam(a))throw Error("Expected template to have key: "+a);});return new gpub.templates.LatexTemplate(b)};gpub.templates.LatexTemplate=function(a){this._template=a};
gpub.templates.LatexTemplate.prototype={setExtraPackages:function(a){this._template.setParam("extraPackages",a);return this},setDiagramTypeDefs:function(a){this._template.setParam("diagramTypeDefs",a);return this},setDiagramWrapperDefs:function(a){this._template.setParam("diagramWrapperDefs",a);return this},setTitleDef:function(a){this._template.setParam("mainBookTitleDef",a);return this},setContent:function(a){this._template.setParam("content",a);return this},compile:function(){return this._template.compile()}};
gpub.templates.parse=function(a){for(var b=[],c={},d="DEFAULT",f=[],e=null,g=0,h=0;h<a.length;h++){var l=a.charAt(h);switch(d){case "DEFAULT":"{"===l?"{"===e&&(b.push(f.join("")),d="IN_PARAM",g++,f=[]):("{"===e&&f.push(e),f.push(l));break;case "IN_PARAM":"}"===l?"}"===e&&(b.push(null),d=f.join("").replace(/^\s*|\s*$/g,""),c[d]=g,g++,d="DEFAULT",f=[]):f.push(l);break;default:throw Error("Unknown state: "+d);}e=l}b.push(f.join(""));return new gpub.templates._Template(b,c)};
