/*
 GPub: A Go publishing platform, built on Glift

 @copyright Josh Hoak
 @license MIT License (see LICENSE.txt)
 --------------------------------------
*/
(function(a){var b=b||a.gpub||{};a&&(a.gpub=b)})(window);gpub.global={version:"0.1.0"};gpub.book={bookFormat:{HTML:"HTML",LATEX:"LATEX"}};gpub.book.htmlBook={create:function(a,b){}};
gpub.book.latex={generate:function(a,b,d){if(!a)throw Error("Options must be defined. Was: "+a);b=b||gpub.templates.latexBase;d=d||gpub.diagrams.diagramType.GOOE;a=glift.widgets.createNoDraw(a);b=gpub.templates.parseLatexTemplate(b);d=gpub.diagrams[glift.enums.toCamelCase(d)].latexHeaders;var c=gpub.diagrams.latex;b.setExtraPackages(d.packageDef()).setDiagramTypeDefs(d.extraDefs()).setDiagramWrapperDefs(c.diagramDefs()).setTitleDef(this.basicTitleDef("Relentless","Gu Li vs Lee Sedol",["Younggil An",
"David Ormerod","Josh Hoak"],"Go Game Guru"));d=[];for(var c=[],e=1,f=1,h=0;h<a.sgfCollection.length;h++){var g=a.loadSgfStringSync(a.getSgfObj(h)),k=glift.rules.movetree.getFromSgf(g.sgfString,g.initialPosition),n=glift.flattener.flatten(k,{nextMovesTreepath:g.nextMovesPath,boardRegion:g.boardRegion}),l=gpub.diagrams.diagramPurpose.GAME_REVIEW;n.isOnMainPath()&&(l=gpub.diagrams.diagramPurpose.GAME_REVIEW_CHAPTER);0==k.node().getNodeNum()&&0==g.nextMovesPath.length&&(l=gpub.diagrams.diagramPurpose.SECTION_INTRO);
g={};l===gpub.diagrams.diagramPurpose.SECTION_INTRO&&(g.sectionTitle=k.getTreeFromRoot().properties().getOneValue("GN")||"",g.chapterTitle="Chapter: "+e,f++,e++);l===gpub.diagrams.diagramPurpose.GAME_REVIEW_CHAPTER&&(g.chapterTitle="Chapter: "+e,e++);k=gpub.diagrams.forPurpose(n,gpub.diagrams.diagramType.GOOE,gpub.book.bookFormat.LATEX,l,g);l===gpub.diagrams.diagramPurpose.SECTION_INTRO||l===gpub.diagrams.diagramPurpose.GAME_REVIEW_CHAPTER?(d.push(gpub.book.latex.renderPage(c)),c=[],c.push(k),d.push(gpub.book.latex.renderPage(c)),
c=[]):(c.push(k),2===c.length&&(d.push(gpub.book.latex.renderPage(c)),c=[]))}return b.setContent(d.join("\n")).compile()},basicTitleDef:function(a,b,d,c){for(var e=["\\definecolor{light-gray}{gray}{0.55}","\\newcommand*{\\mainBookTitle}{\\begingroup","  \\raggedleft"],f=0;f<d.length;f++)e.push("  {\\Large "+d[f]+"} \\\\"),0===f?e.push("  \\vspace*{0.5 em}"):f<d.length-1&&e.push("  \\vspace*{0.5 em}");return e.concat(["  \\vspace*{5 em}","  {\\textcolor{light-gray}{\\Huge "+a+"}}\\\\","  \\vspace*{\\baselineskip}",
"  {\\small \\bfseries "+b+"}\\par","  \\vfill","  {\\Large "+c+"}\\par","  \\vspace*{2\\baselineskip}","\\endgroup}"]).join("\n")},renderPage:function(a){a.push("\\newpage");return a.join("\n")}};
gpub.book.manager={toBook:function(a,b){var d=[],c=glift.enums.showVariations.NEVER,e=gpub.diagrams.gooe,f=gpub.diagrams.latex,h=gpub.book.manager,g=a.bookData;d.push(f.basicHeader());d.push(e.gooeDefs());d.push(f.generateTitleDef(g.title,g.subtitle,g.authors,g.publisher));d.push("");d.push(f.diagramLabelMacros());d.push(f.startDocument());a.prepopulateCache(function(){for(var e=g.diagramsPerPage,n=1,l=1,t=1,p=0,u=a.sgfList.length;p<u;p++){var q=a.getSgfObj(p),v=q.boardRegion,r=glift.rules.treepath.parseInitPosition(q.initialPosition),
s=[];a.getSgfString(q,function(a){var b=glift.rules.movetree.getFromSgf(a.sgfString,r),f=b.onMainline();f?t++:l++;if(g.autoNumber){var m=glift.rules.treepath.findNextMovesPath(b),b=m.movetree;r=m.treepath;s=m.nextMoves}var m=glift.rules.goban.getFromMoveTree(b).goban,p=f?b.node().getNodeNum()+1:1,b=glift.bridge.flattener.flatten(b,m,v,c,s,p),m="";a.bookData.showDiagram&&(m=h.createDiagram(b,a.bookData));f=h.typesetDiagram(m,b.comment,a.bookData,b.collisions,f);!a.bookData.chapterTitle&&n<e?(d.push("\\newpage"),
n++):n=1;d.push(f)})}d.push(f.basicFooter);b(d.join("\n"))})},createDiagram:function(a,b){var d=gpub.diagrams.gooe,c=gpub.diagrams.diagramSize.NORMAL;b.chapterTitle&&(c=gpub.diagrams.diagramSize.LARGE);c=d.diagramArray(a,c);return d.diagramArrToString(c)}};
gpub.spec={specType:{PROBLEM_SET:"PROBLEM_SET",GAME_BOOK:"GAME_BOOK"},fromSgfs:function(a,b){var d=gpub.spec.specType,c={divId:null,sgfCollection:[],sgfMapping:{},sgfDefaults:{}};b=b||d.GAME_BOOK;d=null;switch(b){case "GAME_BOOK":c.sgfDefaults.widgetType="EXAMPLE";d=gpub.spec.allMovetreeVariations;break;case "PROBLEM_SET":c.sgfDefaults.widgetType="STANDARD_PROBLEM";d=gpub.spec.problemSpec;break;default:throw Error("Unknown spec type: "+b);}for(var e=0;a&&e<a.length;e++){var f=a[e],h=glift.sgf.parse(f),
g=h.properties().getOneValue("GN")||"sgf:"+e;c.sgfCollection=c.sgfCollection.concat(d(h,g));c.sgfMapping[g]=f}return c},_fromGames:function(a){for(var b=0;a&&b<a.length;b++){var d=a[b],c=glift.sgf.parse(d),e=c.properties().getOneValue("GN")||"sgf:"+b;spec.sgfMapping[e]=d;spec.sgfCollection=spec.sgfCollection.concat(this.fromMovetree(c,e))}return spec},allMovetreeVariations:function(a,b){for(var d=[],c=[],e=a.node();e;){if(!a.properties().getOneValue("C")&&0<e.numChildren())e=a.node(),c=c.concat(gpub.spec.getVariationPaths(a));
else{var f=glift.rules.treepath.findNextMovesPath(a);d.push(gpub.spec.createExample(b,f.treepath,f.nextMoves));c=c.concat(gpub.spec.getVariationPaths(a));for(f=0;f<c.length;f++){var h=a.getTreeFromRoot(c[f]),h=glift.rules.treepath.findNextMovesPath(h);d.push(gpub.spec.createExample(b,h.treepath,h.nextMoves))}c=[]}e=e.getChild(0);a.moveDown()}return d},getVariationPaths:function(a){a=a.newTreeRef();var b=[];if(!a.node().getParent())return b;a.moveUp();for(var d=1;d<a.node().numChildren();d++){var c=
a.newTreeRef();c.moveDown(d);c.recurse(function(a){a.properties().getOneValue("C")&&b.push(a.treepathToHere())})}return b},createExample:function(a,b,d,c){c=c||glift.enums.boardRegions.ALL;if(!glift.enums.boardRegions[c])throw Error("Unknown board region: "+c);var e=glift.rules.treepath.toInitPathString,f=glift.rules.treepath.toFragmentString;return{widgetType:"EXAMPLE",alias:a,initialPosition:e(b),nextMovesPath:f(d),boardRegion:c}}};
gpub.diagrams={diagramType:{GOOE:"GOOE",IGO:"IGO",PDF:"PDF"},diagramPurpose:{SECTION_INTRO:"SECTION_INTRO",GAME_REVIEW:"GAME_REVIEW",GAME_REVIEW_CHAPTER:"GAME_REVIEW_CHAPTER",PROBLEM:"PROBLEM",PROBLEM_SOLUTION:"PROBLEM_SOLUTION"},sizes:{NORMAL:"NORMAL",LARGE:"LARGE"},forPurpose:function(a,b,d,c,e){if(!b||!gpub.diagrams.diagramType[b])throw Error("Unknown diagram type: "+b);if(!d||!gpub.book.bookFormat[d])throw Error("Unknown diagram type: "+d);if(!c||!gpub.diagrams.diagramPurpose[c])throw Error("Unknown diagram type: "+
c);e=e||{};b=gpub.diagrams.fromFlattened(a,b);var f=null;switch(d){case "LATEX":f=gpub.diagrams.latex;break;default:throw Error("Unsupported book format: "+d);}d=null;switch(c){case "GAME_REVIEW":case "GAME_REVIEW_CHAPTER":case "SECTION_INTRO":d=gpub.diagrams.constructLabel(a.collisions(),a.isOnMainPath(),a.startingMoveNum(),a.endingMoveNum());break;default:d=""}return f.typeset(b,c,a.comment(),d,a.isOnMainPath(),e)},create:function(a,b,d,c,e){a=this.flatten(a,d,c,e);return this.fromFlattened(a,b)},
flatten:function(a,b,d,c){b=b||[];d=d||[];a=glift.rules.movetree.getFromSgf(a,b);return glift.flattener.flatten(a,{nextMovesTreepath:d,boardRegion:c})},fromFlattened:function(a,b){switch(b){case "GOOE":return gpub.diagrams.gooe.create(a);default:throw Error("Not currently supported: "+b);}},constructLabel:function(a,b,d,c){var e="";b&&(b=[d],d!==c&&b.push(c),e+="("+(1<b.length?"Moves: ":"Move: ")+b.join("-")+")");if(a&&a.length){d=[];for(c=0;c<a.length;c++)b=a[c],d.push((b.color===glift.enums.states.BLACK?
"Black":"White")+" "+b.mvnum+" at "+b.label);e&&(e+="\n");e+=d.join(", ")+"."}return e}};
gpub.diagrams.gooe={create:function(a,b){return gpub.diagrams.gooe.gooeStringArray(a,b).join("\n")},gooeStringArray:function(a,b){for(var d="LARGE"===b?"{\\bgoo":"{\\goo",c=gpub.diagrams.gooe.gooeBoard(a,b),d=[d],e=0,c=c.boardArray();e<c.length;e++)d.push(c[e].join(""));d.push("}");return d},gooeBoard:function(a,b){var d=glift.flattener.symbolStr,c=gpub.diagrams.gooe.symbolMap;return a.board().transform(function(a,f,h){f=d(a.base());a.mark()&&a.stone()?f=d(a.stone())+"_"+d(a.mark()):a.stone()?f=d(a.stone()):
a.mark()&&(f=d(a.mark()));h=f+"_"+b;var g="",g=c[h]?c[h]:c[f]?c[f]:c.EMPTY;a.textLabel()&&(g=g.replace("%s",a.textLabel()));return g})}};
gpub.diagrams.gooe.latexHeaders={packageDef:function(){return"\\usepackage{gooemacs}"},defs:{sizeDefs:"% Size definitions;\\newdimen\\bigRaise;\\bigRaise=4.3pt;\\newdimen\\smallRaise;\\smallRaise=3.5pt;\\newdimen\\inlineRaise;\\inlineRaise=3.5pt".split(";"),bigBoardDefs:["% Big-sized board defs","\\def\\eLblBig#1{\\leavevmode\\hbox to \\goIntWd{\\hss\\raise\\bigRaise\\hbox{\\tenpointeleven{#1}}\\hss}}","\\def\\goWsLblBig#1{\\leavevmode\\setbox0=\\hbox{\\0??!}\\rlap{\\0??!}\\raise\\bigRaise\\hbox to \\wd0{\\hss\\tenpointeleven{#1}\\hss}}",
"\\def\\goBsLblBig#1{\\leavevmode\\setbox0=\\hbox{\\0??@}\\rlap{\\0??@}\\raise\\bigRaise\\hbox to \\wd0{\\hss\\color{white}\\tenpointeleven{#1}\\color{white}\\hss}}"],normalBoardDefs:["% Normal-sized board defs","\\def\\eLbl#1{\\leavevmode\\hbox to \\goIntWd{\\hss\\raise\\smallRaise\\hbox{\\tenpoint{#1}}\\hss}}","\\def\\goWsLbl#1{\\leavevmode\\setbox0=\\hbox{\\0??!}\\rlap{\\0??!}\\raise\\smallRaise\\hbox to \\wd0{\\hss\\eightpointnine{#1}\\hss}}","\\def\\goBsLbl#1{\\leavevmode\\setbox0=\\hbox{\\0??@}\\rlap{\\0??@}\\raise\\smallRaise\\hbox to \\wd0{\\hss\\color{white}\\eightpointnine{#1}\\color{white}\\hss}}"]},
extraDefs:function(a){var b=gpub.diagrams.gooe.latexHeaders.defs;a=a||"cmss";return["% Gooe font definitions","\\font\\tenpoint="+a+"10","\\font\\tenpointeleven="+a+"10 at 11pt","\\font\\eightpoint="+a+"8","\\font\\eightpointnine="+a+"8 at 9pt"].concat(b.sizeDefs).concat(b.bigBoardDefs).concat(b.normalBoardDefs).join("\n")}};
gpub.diagrams.gooe.symbolMap={EMPTY:"\\eLbl{_}",TL_CORNER:"\\0??<",TR_CORNER:"\\0??>",BL_CORNER:"\\0??,",BR_CORNER:"\\0??.",TOP_EDGE:"\\0??(",BOT_EDGE:"\\0??)",LEFT_EDGE:"\\0??[",RIGHT_EDGE:"\\0??]",CENTER:"\\0??+",CENTER_STARPOINT:"\\0??*",BSTONE:"\\0??@",WSTONE:"\\0??!",BSTONE_TRIANGLE:"\\0??S",WSTONE_TRIANGLE:"\\0??s",TRIANGLE:"\\0??3",BSTONE_SQUARE:"\\0??S",WSTONE_SQUARE:"\\0??s",SQUARE:"\\0??2",BSTONE_CIRCLE:"\\0??C",WSTONE_CIRCLE:"\\0??c",CIRCLE:"\\0??1",BSTONE_XMARK:"\\0??X",WSTONE_XMARK:"\\0??x",
XMARK:"\\0??4",BSTONE_TEXTLABEL:"\\goBsLbl{%s}",WSTONE_TEXTLABEL:"\\goWsLbl{%s}",TEXTLABEL:"\\eLbl{%s}",BSTONE_TEXTLABEL_LARGE:"\\goBsLblBig{%s}",WSTONE_TEXTLABEL_LARGE:"\\goWsLblBig{%s}",TEXTLABEL_LARGE:"\\eLblBig{%s}"};gpub.diagrams.igo={create:function(a){}};gpub.diagrams.pdf={create:function(a){}};
gpub.diagrams.latex={sanitize:function(a){return a.replace(/[$#}{]/g,function(a){return"\\"+a})},typeset:function(a,b,d,c,e,f){d=this.sanitize(d);var h=glift.enums.toCamelCase(b),h=gpub.diagrams.latex[h];switch(b){case "GAME_REVIEW":case "GAME_REVIEW_CHAPTER":b=e?"\\gofigure":"\\godiagram";if(c)for(c=c.split("\n"),e=0;e<c.length;e++)b+="\n\n\\subtext{"+c[e]+"}";c=b}return h(a,d,c,f)},sectionIntro:function(a,b,d,c){return["\\part{"+(c.sectionTitle||"")+"}","\\chapter{"+(c.chapterTitle||"")+"}",b].join("\n")},
gameReview:function(a,b,d){return["\n\\rule{\\textwidth}{0.5pt}\n\n\\begin{minipage}[t]{0.5\\textwidth}",a,d,"\\end{minipage}\n\\begin{minipage}[t]{0.5\\textwidth}\n\\setlength{\\parskip}{0.5em}",b,"\\end{minipage}\n\\vfill"].join("\n")},gameReviewChapter:function(a,b,d,c){return["\\chapter{"+c.chapterTitle+"}","{\\centering",a,"}",d,"",b,"\\vfill"].join("\n")}};gpub.diagrams.latex.diagramDefs=function(a){return"% Mainline Diagrams. reset at parts\n\\newcounter{GoFigure}[part]\n\\newcommand{\\gofigure}{%\n \\stepcounter{GoFigure}\n \\centerline{\\textit{Figure.\\thinspace\\arabic{GoFigure}}}\n}\n% Variation Diagrams. reset at parts.\n\\newcounter{GoDiagram}[part]\n\\newcommand{\\godiagram}{%\n \\stepcounter{GoDiagram}\n \\centerline{\\textit{Diagram.\\thinspace\\arabic{GoDiagram}}}\n}\n\\newcommand{\\subtext}[1]{\\centerline{\\textit{#1}}}\n"};
gpub.templates={};gpub.templates._Template=function(a,b){this._sections=a;this._paramMap=b;this._paramContent={}};gpub.templates._Template.prototype={compile:function(){var a=this._sections.slice(0),b;for(b in this._paramMap)a[this._paramMap[b]]=this._paramContent[b]||"";return a.join("")},hasParam:function(a){return!!this._paramMap[a]},setParam:function(a,b){if(!this._paramMap[a])throw Error("Unknown key: "+a);this._paramContent[a]=b.toString()}};gpub.templates.latexBase="\\documentclass[letterpaper,12pt]{memoir}\n\\usepackage{color}\n\\usepackage{wrapfig}\n\\usepackage{setspace}\n\\usepackage{unicode}\n\\usepackage[margin=1in]{geometry}\n%%% Define any extra packages %%%\n{{ extraPackages }}\n\n\\setlength{\\parskip}{0.5em}\n\\setlength{\\parindent}{0pt}\n\n%%% Extra defs\n% Necessary for the particular digaram type.\n{{ diagramTypeDefs }}\n\n%%% Diagram Figure defs.\n% Must expose two commands\n%  \\gofigure  (mainline diagrams)\n%  \\godiagram (variation diagrams)\n{{ diagramWrapperDefs }}\n\n%%% Define the main title %%%\n{{ mainBookTitleDef }}\n\n\\begin{document}\n\n\\pagestyle{empty}\n\\mainBookTitle\n\\newpage\n\\tableofcontents\n\n\\chapterstyle{section}\n\\pagestyle{companion}\n\\makepagestyle{headings}\n\\renewcommand{\\printchapternum}{\\space}\n\\makeevenhead{headings}{\\thepage}{}{\\slshape\\leftmark}\n\\makeoddhead{headings}{\\slshape\\rightmark}{}{\\thepage}\n\n%%% The content. %%%\n{{ content }}\n\n\\end{document}";
gpub.templates.parseLatexTemplate=function(a){var b=gpub.templates.parse(a);["extraPackages","diagramTypeDefs","diagramWrapperDefs","mainBookTitleDef","content"].forEach(function(a){if(!b.hasParam(a))throw Error("Expected template to have key: "+a);});return new gpub.templates.LatexTemplate(b)};gpub.templates.LatexTemplate=function(a){this._template=a};
gpub.templates.LatexTemplate.prototype={setExtraPackages:function(a){this._template.setParam("extraPackages",a);return this},setDiagramTypeDefs:function(a){this._template.setParam("diagramTypeDefs",a);return this},setDiagramWrapperDefs:function(a){this._template.setParam("diagramWrapperDefs",a);return this},setTitleDef:function(a){this._template.setParam("mainBookTitleDef",a);return this},setContent:function(a){this._template.setParam("content",a);return this},compile:function(){return this._template.compile()}};
gpub.templates.parse=function(a){for(var b=[],d={},c="DEFAULT",e=[],f=null,h=0,g=0;g<a.length;g++){var k=a.charAt(g);switch(c){case "DEFAULT":"{"===k?"{"===f&&(b.push(e.join("")),c="IN_PARAM",h++,e=[]):("{"===f&&e.push(f),e.push(k));break;case "IN_PARAM":"}"===k?"}"===f&&(b.push(null),c=e.join("").replace(/^\s*|\s*$/g,""),d[c]=h,h++,c="DEFAULT",e=[]):e.push(k);break;default:throw Error("Unknown state: "+c);}f=k}b.push(e.join(""));return new gpub.templates._Template(b,d)};
