/*
 GPub: A Go publishing platform, built on Glift

 @copyright Josh Hoak
 @license MIT License (see LICENSE.txt)
 --------------------------------------
*/
(function(a){var b=b||a.gpub||{};a&&(a.gpub=b)})(window);gpub.global={version:"0.1.0"};gpub.util={};gpub.util.Buffer=function(a){this._maxSize=a||1;this._buffer=[]};gpub.util.Buffer.prototype={add:function(a){null!=a&&this._buffer.push(a);return this},atCapacity:function(){return this._buffer.length>=this._maxSize},flush:function(){var a=this._buffer.slice(0);this._buffer=[];return a}};gpub.book={bookFormat:{HTML:"HTML",LATEX:"LATEX"}};gpub.book.htmlBook={create:function(a,b){}};
gpub.book.latex={generate:function(a,b,c,d){if(!a)throw Error("Options must be defined. Was: "+a);b=b||gpub.templates.latexBase;c=c||gpub.diagrams.diagramType.GOOE;a=glift.widgets.createNoDraw(a);b=gpub.templates.parseLatexTemplate(b);d=gpub.diagrams[glift.enums.toCamelCase(c)].latexHeaders;var e=gpub.diagrams.latex;b.setExtraPackages(d.packageDef()).setDiagramTypeDefs(d.extraDefs()).setDiagramWrapperDefs(e.diagramDefs()).setTitleDef(this.basicTitleDef("Relentless","Gu Li vs Lee Sedol",["Younggil An",
"David Ormerod","Josh Hoak"],"Go Game Guru"));d=[];for(var e=[],f=1,g=1,h=null,l=gpub.diagrams.diagramPurpose,m=0;m<a.sgfCollection.length;m++){var k=a.loadSgfStringSync(a.getSgfObj(m)),n=glift.rules.movetree.getFromSgf(k.sgfString,k.initialPosition),p=glift.flattener.flatten(n,{nextMovesTreepath:k.nextMovesPath,boardRegion:k.boardRegion}),k=gpub.book.NodeData.fromContext(n,p,k.metadata,k.nextMovesPath||[]),g=k.setSectionFromCtx(n,h,g),f=k.setChapterFromCtx(n,h,f),n=gpub.diagrams.forPurpose(p,c,gpub.book.bookFormat.LATEX,
k.purpose,k);k.purpose===l.SECTION_INTRO||k.purpose===l.GAME_REVIEW_CHAPTER||k.purpose!==h?(d.push(gpub.book.latex.renderPage(e)),e=[],e.push(n),d.push(gpub.book.latex.renderPage(e)),e=[]):(e.push(n),2===e.length&&(d.push(gpub.book.latex.renderPage(e)),e=[]));h=k.purpose}return b.setContent(d.join("\n")).compile()},basicTitleDef:function(a,b,c,d){for(var e=["\\definecolor{light-gray}{gray}{0.55}","\\newcommand*{\\mainBookTitle}{\\begingroup","  \\raggedleft"],f=0;f<c.length;f++)e.push("  {\\Large "+
c[f]+"} \\\\"),0===f?e.push("  \\vspace*{0.5 em}"):f<c.length-1&&e.push("  \\vspace*{0.5 em}");return e.concat(["  \\vspace*{5 em}","  {\\textcolor{light-gray}{\\Huge "+a+"}}\\\\","  \\vspace*{\\baselineskip}","  {\\small \\bfseries "+b+"}\\par","  \\vfill","  {\\Large "+d+"}\\par","  \\vspace*{2\\baselineskip}","\\endgroup}"]).join("\n")},renderPage:function(a){a.push("\\newpage");return a.join("\n")}};
gpub.book.manager={toBook:function(a,b){var c=[],d=glift.enums.showVariations.NEVER,e=gpub.diagrams.gooe,f=gpub.diagrams.latex,g=gpub.book.manager,h=a.bookData;c.push(f.basicHeader());c.push(e.gooeDefs());c.push(f.generateTitleDef(h.title,h.subtitle,h.authors,h.publisher));c.push("");c.push(f.diagramLabelMacros());c.push(f.startDocument());a.prepopulateCache(function(){for(var e=h.diagramsPerPage,m=1,k=1,n=1,p=0,u=a.sgfList.length;p<u;p++){var r=a.getSgfObj(p),v=r.boardRegion,s=glift.rules.treepath.parseInitPosition(r.initialPosition),
t=[];a.getSgfString(r,function(a){var b=glift.rules.movetree.getFromSgf(a.sgfString,s),f=b.onMainline();f?n++:k++;if(h.autoNumber){var q=glift.rules.treepath.findNextMovesPath(b),b=q.movetree;s=q.treepath;t=q.nextMoves}var q=glift.rules.goban.getFromMoveTree(b).goban,p=f?b.node().getNodeNum()+1:1,b=glift.bridge.flattener.flatten(b,q,v,d,t,p),q="";a.bookData.showDiagram&&(q=g.createDiagram(b,a.bookData));f=g.typesetDiagram(q,b.comment,a.bookData,b.collisions,f);!a.bookData.chapterTitle&&m<e?(c.push("\\newpage"),
m++):m=1;c.push(f)})}c.push(f.basicFooter);b(c.join("\n"))})},createDiagram:function(a,b){var c=gpub.diagrams.gooe,d=gpub.diagrams.diagramSize.NORMAL;b.chapterTitle&&(d=gpub.diagrams.diagramSize.LARGE);d=c.diagramArray(a,d);return c.diagramArrToString(d)}};gpub.book.NodeData=function(a){if(!gpub.diagrams.diagramPurpose[a])throw Error("Purpose not defined in gpub.diagrams.diagramPurpose: "+a);this.purpose=a;this.sectionTitle=null;this.sectionNumber=-1;this.chapterTitle=null;this.chapterNumber=-1};
gpub.book.NodeData.prototype={setSectionFromCtx:function(a,b,c){return this.purpose===gpub.diagrams.diagramPurpose.SECTION_INTRO?(this.sectionTitle=a.getTreeFromRoot().properties().getOneValue("GN")||"",this.sectionNumber=c,c+1):c},setChapterFromCtx:function(a,b,c){a=gpub.diagrams.diagramPurpose;return this.purpose===a.GAME_REVIEW_CHAPTER||(this.purpose===a.PROBLEM||this.purpose===a.ANSWER)&&this.purpose!==b?(this.chapterTitle="Chapter: "+c,this.chapterNumber=c,c+1):c}};
gpub.book.NodeData.fromContext=function(a,b,c,d){var e=gpub.diagrams.diagramPurpose,f=e.GAME_REVIEW;c=c||{};e[c.exampleType]&&(f=c.exampleType);0===a.node().getNodeNum()&&0===d.length&&f===e.GAME_REVIEW&&(f=gpub.diagrams.diagramPurpose.SECTION_INTRO);b.isOnMainPath()&&f===e.GAME_REVIEW&&(f=gpub.diagrams.diagramPurpose.GAME_REVIEW_CHAPTER);return new gpub.book.NodeData(f)};
gpub.spec={specType:{PROBLEM_SET:"PROBLEM_SET",PROBLEM_BOOK:"PROBLEM_BOOK",GAME_BOOK:"GAME_BOOK"},exampleType:{PROBLEM:"PROBLEM",ANSWER:"ANSWER",GAME_REVIEW:"GAME_REVIEW"},fromSgfs:function(a,b,c){var d=gpub.spec.specType;c=c||{};var e=b||d.GAME_BOOK;b={divId:null,sgfCollection:[],sgfMapping:{},sgfDefaults:{},metadata:{specType:e}};var f=1,d=null;switch(e){case "GAME_BOOK":b.sgfDefaults.widgetType="EXAMPLE";f=1;d=function(a,b){return gpub.spec.gameBook.one(a[0].movetree,a[0].name,b)};break;case "PROBLEM_SET":b.sgfDefaults.widgetType=
"STANDARD_PROBLEM";f=1;d=function(a,b){return gpub.spec.problemSet.one(a[0].movetree,a[0].name,b)};break;case "PROBLEM_BOOK":b.sgfDefaults.widgetType="EXAMPLE";d=gpub.spec.problemBook.multi;e=gpub.spec.problemBook.answerStyle;c.answerStyle=c.answerStyle||e.END_OF_SECTION;f=c.answerStyle===e.END_OF_SECTION?a.length:c.answerStyle===e.AFTER_PAGE?c.bufferSize||4:1;break;default:throw Error("Unknown spec type: "+e);}e=new gpub.util.Buffer(f);for(f=0;a&&f<a.length;f++){var g=a[f],h=glift.parse.fromString(g),
l=h.properties().getOneValue("GN")||"sgf:"+f;e.add({movetree:h,name:l});if(e.atCapacity()||f===a.length-1)b.sgfCollection=b.sgfCollection.concat(d(e.flush(),c));b.sgfMapping[l]=g}return b},createExample:function(a,b,c,d,e){d=d||glift.enums.boardRegions.ALL;if(!glift.enums.boardRegions[d])throw Error("Unknown board region: "+d);var f=gpub.spec.exampleType,g=glift.rules.treepath.toInitPathString,h=glift.rules.treepath.toFragmentString;a={widgetType:"EXAMPLE",alias:a,initialPosition:g(b),nextMovesPath:h(c),
boardRegion:d};e&&f[e]&&(a.metadata={exampleType:e});return a}};
gpub.spec.gameBook={one:function(a,b,c){c=[];for(var d=[],e=a.node();e;){if(!a.properties().getOneValue("C")&&0<e.numChildren())e=a.node(),d=d.concat(gpub.spec.gameBook.variationPaths(a));else{var f=glift.rules.treepath.findNextMovesPath(a);c.push(gpub.spec.createExample(b,f.treepath,f.nextMoves));d=d.concat(gpub.spec.gameBook.variationPaths(a));for(f=0;f<d.length;f++){var g=a.getTreeFromRoot(d[f]),g=glift.rules.treepath.findNextMovesPath(g);c.push(gpub.spec.createExample(b,g.treepath,g.nextMoves))}d=
[]}e=e.getChild(0);a.moveDown()}return c},variationPaths:function(a){a=a.newTreeRef();var b=[];if(!a.node().getParent())return b;a.moveUp();for(var c=1;c<a.node().numChildren();c++){var d=a.newTreeRef();d.moveDown(c);d.recurse(function(a){a.properties().getOneValue("C")&&b.push(a.treepathToHere())})}return b}};
gpub.spec.problemBook={answerStyle:{NONE:"NONE",END_OF_SECTION:"END_OF_SECTION",AFTER_PAGE:"END_OF_SECTION"},fromProblemSet:function(a){},multi:function(a,b){b=b||{};for(var c=b.numAnswerVars||3,d=[],e=[],f=b.region||glift.enums.boardRegions.AUTO,g=0;g<a.length;g++){var h=a[g].movetree.newTreeRef(),l=a[g].name,m=gpub.spec.createExample(l,[],[],f,"PROBLEM");d.push(m);h=gpub.spec.problemBook.variationPaths(h,c);for(m=0;m<h.length;m++){var k=gpub.spec.createExample(l,"",h[m],f,"ANSWER");e.push(k)}}return d.concat(e)},
variationPaths:function(a,b){var c=[];if(0===b)return c;a.recurseFromRoot(function(a){0===a.node().numChildren()&&c.push(a.treepathToHere())});return 0>b?c:c.slice(0,b)}};gpub.spec.problemSet={one:function(a,b,c){region=c.region||glift.enums.boardRegions.AUTO;return{alias:b,widgetType:"STANDARD_PROBLEM",boardRegion:region}}};
gpub.diagrams={diagramType:{GOOE:"GOOE",GNOS:"GNOS",IGO:"IGO",PDF:"PDF"},diagramPurpose:{SECTION_INTRO:"SECTION_INTRO",GAME_REVIEW:"GAME_REVIEW",GAME_REVIEW_CHAPTER:"GAME_REVIEW_CHAPTER",PROBLEM:"PROBLEM",ANSWER:"ANSWER"},sizes:{NORMAL:"NORMAL",LARGE:"LARGE"},forPurpose:function(a,b,c,d,e){if(!b||!gpub.diagrams.diagramType[b])throw Error("Unknown diagram type: "+b);if(!c||!gpub.book.bookFormat[c])throw Error("Unknown diagram type: "+c);if(!d||!gpub.diagrams.diagramPurpose[d])throw Error("Unknown diagram type: "+
d);e=e||{};b=gpub.diagrams.fromFlattened(a,b);var f=null;switch(c){case "LATEX":f=gpub.diagrams.latex;break;default:throw Error("Unsupported book format: "+c);}c=null;switch(d){case "GAME_REVIEW":case "GAME_REVIEW_CHAPTER":case "SECTION_INTRO":c=gpub.diagrams.constructLabel(a.collisions(),a.isOnMainPath(),a.startingMoveNum(),a.endingMoveNum());break;default:c=""}return f.typeset(b,d,a.comment(),c,a.isOnMainPath(),e)},create:function(a,b,c,d,e){a=this.flatten(a,c,d,e);return this.fromFlattened(a,b)},
flatten:function(a,b,c,d){b=b||[];c=c||[];a=glift.rules.movetree.getFromSgf(a,b);return glift.flattener.flatten(a,{nextMovesTreepath:c,boardRegion:d})},fromFlattened:function(a,b){switch(b){case "GOOE":return gpub.diagrams.gooe.create(a);case "GNOS":return gpub.diagrams.gnos.create(a);default:throw Error("Not currently supported: "+b);}},constructLabel:function(a,b,c,d){var e="";b&&(b=[c],c!==d&&b.push(d),e+="("+(1<b.length?"Moves: ":"Move: ")+b.join("-")+")");if(a&&a.length){c=[];for(d=0;d<a.length;d++)b=
a[d],c.push((b.color===glift.enums.states.BLACK?"Black":"White")+" "+b.mvnum+" at "+b.label);e&&(e+="\n");e+=c.join(", ")+"."}return e}};
gpub.diagrams.gooe={create:function(a,b){return gpub.diagrams.gooe.gooeStringArray(a,b).join("\n")},gooeStringArray:function(a,b){for(var c="LARGE"===b?"{\\bgoo":"{\\goo",d=gpub.diagrams.gooe.gooeBoard(a,b),c=[c],e=0,d=d.boardArray();e<d.length;e++)c.push(d[e].join(""));c.push("}");return c},gooeBoard:function(a,b){var c=glift.flattener.symbolStr,d=gpub.diagrams.gooe.symbolMap;return a.board().transform(function(a,f,g){f=c(a.base());a.mark()&&a.stone()?f=c(a.stone())+"_"+c(a.mark()):a.stone()?f=c(a.stone()):
a.mark()&&(f=c(a.mark()));g=f+"_"+b;var h="",h=d[g]?d[g]:d[f]?d[f]:d.EMPTY;a.textLabel()&&(h=h.replace("%s",a.textLabel()));return h})}};
gpub.diagrams.gooe.latexHeaders={packageDef:function(){return"\\usepackage{gooemacs}"},defs:{sizeDefs:"% Size definitions;\\newdimen\\bigRaise;\\bigRaise=4.3pt;\\newdimen\\smallRaise;\\smallRaise=3.5pt;\\newdimen\\inlineRaise;\\inlineRaise=3.5pt".split(";"),bigBoardDefs:["% Big-sized board defs","\\def\\eLblBig#1{\\leavevmode\\hbox to \\goIntWd{\\hss\\raise\\bigRaise\\hbox{\\tenpointeleven{#1}}\\hss}}","\\def\\goWsLblBig#1{\\leavevmode\\setbox0=\\hbox{\\0??!}\\rlap{\\0??!}\\raise\\bigRaise\\hbox to \\wd0{\\hss\\tenpointeleven{#1}\\hss}}",
"\\def\\goBsLblBig#1{\\leavevmode\\setbox0=\\hbox{\\0??@}\\rlap{\\0??@}\\raise\\bigRaise\\hbox to \\wd0{\\hss\\color{white}\\tenpointeleven{#1}\\color{white}\\hss}}"],normalBoardDefs:["% Normal-sized board defs","\\def\\eLbl#1{\\leavevmode\\hbox to \\goIntWd{\\hss\\raise\\smallRaise\\hbox{\\tenpoint{#1}}\\hss}}","\\def\\goWsLbl#1{\\leavevmode\\setbox0=\\hbox{\\0??!}\\rlap{\\0??!}\\raise\\smallRaise\\hbox to \\wd0{\\hss\\eightpointnine{#1}\\hss}}","\\def\\goBsLbl#1{\\leavevmode\\setbox0=\\hbox{\\0??@}\\rlap{\\0??@}\\raise\\smallRaise\\hbox to \\wd0{\\hss\\color{white}\\eightpointnine{#1}\\color{white}\\hss}}"]},
extraDefs:function(a){var b=gpub.diagrams.gooe.latexHeaders.defs;a=a||"cmss";return["% Gooe font definitions","\\font\\tenpoint="+a+"10","\\font\\tenpointeleven="+a+"10 at 11pt","\\font\\eightpoint="+a+"8","\\font\\eightpointnine="+a+"8 at 9pt"].concat(b.sizeDefs).concat(b.bigBoardDefs).concat(b.normalBoardDefs).join("\n")}};
gpub.diagrams.gooe.symbolMap={EMPTY:"\\eLbl{_}",TL_CORNER:"\\0??<",TR_CORNER:"\\0??>",BL_CORNER:"\\0??,",BR_CORNER:"\\0??.",TOP_EDGE:"\\0??(",BOT_EDGE:"\\0??)",LEFT_EDGE:"\\0??[",RIGHT_EDGE:"\\0??]",CENTER:"\\0??+",CENTER_STARPOINT:"\\0??*",BSTONE:"\\0??@",WSTONE:"\\0??!",BSTONE_TRIANGLE:"\\0??S",WSTONE_TRIANGLE:"\\0??s",TRIANGLE:"\\0??3",BSTONE_SQUARE:"\\0??S",WSTONE_SQUARE:"\\0??s",SQUARE:"\\0??2",BSTONE_CIRCLE:"\\0??C",WSTONE_CIRCLE:"\\0??c",CIRCLE:"\\0??1",BSTONE_XMARK:"\\0??X",WSTONE_XMARK:"\\0??x",
XMARK:"\\0??4",BSTONE_TEXTLABEL:"\\goBsLbl{%s}",WSTONE_TEXTLABEL:"\\goWsLbl{%s}",TEXTLABEL:"\\eLbl{%s}",BSTONE_TEXTLABEL_LARGE:"\\goBsLblBig{%s}",WSTONE_TEXTLABEL_LARGE:"\\goWsLblBig{%s}",TEXTLABEL_LARGE:"\\eLblBig{%s}"};
gpub.diagrams.gnos={sizes:{8:"8",9:"9",10:"10",11:"11",12:"12",14:"14",16:"16",20:"20"},sizeToModAtTen:{8:"tiny",9:"scriptsize",10:"scriptsize",11:"footnotesize",12:"footnotesize",14:"small",16:"normalsize",20:"Large"},sizeToModAtTwelve:{8:"tiny",9:"scriptsize",10:"scriptsize",11:"footnotesize",12:"footnotesize",14:"small",16:"normalsize",20:"Large"},create:function(a,b){b=b||gpub.diagrams.gnos.sizes["12"];return gpub.diagrams.gnos.gnosStringArr(a,b).join("\n")},createSimple:function(a,b){b=b||gpub.diagrams.gnos.sizes["12"];
return gpub.diagrams.gnos.gnosStringArrSimple(a,b).join("\n")},gnosStringArrSimple:function(a,b){for(var c=["\\gnosfontsize{"+b+"}","\\gnos"],d=0,e=gpub.diagrams.gnos.gnosBoard(a,b).boardArray();d<e.length;d++)c.push(e[d].join("")+"\\\\");return c},gnosStringArr:function(a,b){for(var c=["\\gnosfontsize{"+b+"}","{\\gnos"],d=0,e=gpub.diagrams.gnos.gnosBoard(a,b).boardArray();d<e.length;d++)c.push(e[d].join("")+"\\\\");c.push("}");return c},gnosBoard:function(a,b){var c=glift.flattener.symbolStr,d=gpub.diagrams.gnos.symbolMap;
return a.board().transform(function(a,f,g){f=c(a.base());a.textLabel()&&a.mark()&&a.mark()===glift.flattener.symbols.TEXTLABEL?f=gpub.diagrams.gnos.getLabelDef(a.textLabel(),a.stone(),b):a.mark()&&a.stone()?f=c(a.stone())+"_"+c(a.mark()):a.stone()?f=c(a.stone()):a.mark()&&(f=c(a.mark()));out=d[f]?d[f]:d.EMPTY;if(a=a.textLabel())/^\d+$/.test(a)&&/NUMLABEL/.test(f)&&(a=parseInt(a)%100),out=out.replace("%s",a);return out})},getLabelDef:function(a,b,c){c=glift.flattener.symbolStr;if(/^\d+$/.test(a)&&
b){a=parseInt(a);b=c(b);if(0<a&&100>a)return b+"_NUMLABEL_1_99";if(100<=a&&200>a)return b+"_NUMLABEL_100_199";if(200<=a&&299>a)return b+"_NUMLABEL_200_299";if(300<=a&&399>a)return b+"_NUMLABEL_300_399"}else return b&&a?c(b)+"_TEXTLABEL":"TEXTLABEL"}};gpub.diagrams.gnos.latexHeaders={packageDef:function(){return"\\usepackage{gnos}"},extraDefs:function(a){return""}};
gpub.diagrams.gnos.symbolMap={EMPTY:"\\gnosEmptyLbl{_}",TL_CORNER:"<",TR_CORNER:">",BL_CORNER:",",BR_CORNER:".",TOP_EDGE:"(",BOT_EDGE:")",LEFT_EDGE:"\\char91",RIGHT_EDGE:"]",CENTER:"+",CENTER_STARPOINT:"*",BSTONE:"@",WSTONE:"!",BSTONE_TRIANGLE:"S",WSTONE_TRIANGLE:"s",TRIANGLE:"3",BSTONE_SQUARE:"S",WSTONE_SQUARE:"s",SQUARE:"2",BSTONE_CIRCLE:"C",WSTONE_CIRCLE:"c",CIRCLE:"1",BSTONE_XMARK:"X",WSTONE_XMARK:"x",XMARK:"4",BSTONE_TEXTLABEL:"\\gnosOverlap{@}{\\color{white}%s}",WSTONE_TEXTLABEL:"\\gnosOverlap{!}{%s}",
TEXTLABEL:"\\gnosEmptyLbl{%s}",BSTONE_NUMLABEL_1_99:"{\\gnosb\\char%s}",BSTONE_NUMLABEL_100_199:"{\\gnosbi\\char%s}",BSTONE_NUMLABEL_200_299:"{\\gnosbii\\char%s}",BSTONE_NUMLABEL_300_399:"{\\gnosbiii\\char%s}",WSTONE_NUMLABEL_1_99:"{\\gnosw\\char%s}",WSTONE_NUMLABEL_100_199:"{\\gnoswi\\char%s}",WSTONE_NUMLABEL_200_299:"{\\gnoswii\\char%s}",WSTONE_NUMLABEL_300_399:"{\\gnoswiii\\char%s}"};gpub.diagrams.igo={create:function(a){}};gpub.diagrams.pdf={create:function(a){}};
gpub.diagrams.latex={sanitize:function(a){return a.replace(/[$#}{]/g,function(a){return"\\"+a})},typeset:function(a,b,c,d,e,f){c=this.sanitize(c);var g=glift.enums.toCamelCase(b),g=gpub.diagrams.latex[g];switch(b){case "GAME_REVIEW":case "GAME_REVIEW_CHAPTER":b=e?"\\gofigure":"\\godiagram";if(d)for(d=d.split("\n"),e=0;e<d.length;e++)b+="\n\n\\subtext{"+d[e]+"}";d=b}return g(a,c,d,f)},sectionIntro:function(a,b,c,d){return["\\part{"+(d.sectionTitle||"")+"}","\\chapter{"+(d.chapterTitle||"")+"}",b].join("\n")},
gameReview:function(a,b,c){return["\n\\rule{\\textwidth}{0.5pt}\n\n\\begin{minipage}[t]{0.5\\textwidth}",a,c,"\\end{minipage}\n\\begin{minipage}[t]{0.5\\textwidth}\n\\setlength{\\parskip}{0.5em}",b,"\\end{minipage}\n\\vfill"].join("\n")},gameReviewChapter:function(a,b,c,d){return["\\chapter{"+d.chapterTitle+"}","{\\centering",a,"}",c,"",b,"\\vfill"].join("\n")},problem:function(a,b,c,d){return[a,c,"",b].join("\n")},answer:function(a,b,c,d){return[a,c,"",b].join("\n")}};
gpub.diagrams.latex.diagramDefs=function(a){return"% Mainline Diagrams. reset at parts\n\\newcounter{GoFigure}[part]\n\\newcommand{\\gofigure}{%\n \\stepcounter{GoFigure}\n \\centerline{\\textit{Figure.\\thinspace\\arabic{GoFigure}}}\n}\n% Variation Diagrams. reset at parts.\n\\newcounter{GoDiagram}[part]\n\\newcommand{\\godiagram}{%\n \\stepcounter{GoDiagram}\n \\centerline{\\textit{Diagram.\\thinspace\\arabic{GoDiagram}}}\n}\n\\newcommand{\\subtext}[1]{\\centerline{\\textit{#1}}}\n"};
gpub.templates={};gpub.templates._Template=function(a,b){this._sections=a;this._paramMap=b;this._paramContent={}};gpub.templates._Template.prototype={compile:function(){var a=this._sections.slice(0),b;for(b in this._paramMap)a[this._paramMap[b]]=this._paramContent[b]||"";return a.join("")},hasParam:function(a){return!!this._paramMap[a]},setParam:function(a,b){if(!this._paramMap[a])throw Error("Unknown key: "+a);this._paramContent[a]=b.toString()}};gpub.templates.latexBase="\\documentclass[letterpaper,12pt]{memoir}\n\\usepackage{color}\n\\usepackage{wrapfig}\n\\usepackage{setspace}\n\\usepackage{unicode}\n\\usepackage[margin=1in]{geometry}\n%%% Define any extra packages %%%\n{{ extraPackages }}\n\n\\setlength{\\parskip}{0.5em}\n\\setlength{\\parindent}{0pt}\n\n%%% Extra defs\n% Necessary for the particular digaram type.\n{{ diagramTypeDefs }}\n\n%%% Diagram Figure defs.\n% Must expose two commands\n%  \\gofigure  (mainline diagrams)\n%  \\godiagram (variation diagrams)\n{{ diagramWrapperDefs }}\n\n%%% Define the main title %%%\n{{ mainBookTitleDef }}\n\n\\begin{document}\n\n\\pagestyle{empty}\n\\mainBookTitle\n\\newpage\n\\tableofcontents\n\n\\chapterstyle{section}\n\\pagestyle{companion}\n\\makepagestyle{headings}\n\\renewcommand{\\printchapternum}{\\space}\n\\makeevenhead{headings}{\\thepage}{}{\\slshape\\leftmark}\n\\makeoddhead{headings}{\\slshape\\rightmark}{}{\\thepage}\n\n%%% The content. %%%\n{{ content }}\n\n\\end{document}";
gpub.templates.parseLatexTemplate=function(a){var b=gpub.templates.parse(a);["extraPackages","diagramTypeDefs","diagramWrapperDefs","mainBookTitleDef","content"].forEach(function(a){if(!b.hasParam(a))throw Error("Expected template to have key: "+a);});return new gpub.templates.LatexTemplate(b)};gpub.templates.LatexTemplate=function(a){this._template=a};
gpub.templates.LatexTemplate.prototype={setExtraPackages:function(a){this._template.setParam("extraPackages",a);return this},setDiagramTypeDefs:function(a){this._template.setParam("diagramTypeDefs",a);return this},setDiagramWrapperDefs:function(a){this._template.setParam("diagramWrapperDefs",a);return this},setTitleDef:function(a){this._template.setParam("mainBookTitleDef",a);return this},setContent:function(a){this._template.setParam("content",a);return this},compile:function(){return this._template.compile()}};
gpub.templates.parse=function(a){for(var b=[],c={},d="DEFAULT",e=[],f=null,g=0,h=0;h<a.length;h++){var l=a.charAt(h);switch(d){case "DEFAULT":"{"===l?"{"===f&&(b.push(e.join("")),d="IN_PARAM",g++,e=[]):("{"===f&&e.push(f),e.push(l));break;case "IN_PARAM":"}"===l?"}"===f&&(b.push(null),d=e.join("").replace(/^\s*|\s*$/g,""),c[d]=g,g++,d="DEFAULT",e=[]):e.push(l);break;default:throw Error("Unknown state: "+d);}f=l}b.push(e.join(""));return new gpub.templates._Template(b,c)};
